### ISSUE TITLE
Sandbox/test environment

### ISSUE THREAD

**Issue by shalak** [blackberrymamba/ChomikDownloader#1]
Hi, @plintx!

I'm thinking of wrapping this into some kind of docker solution with web GUI, similar to [metube](https://github.com/alexta69/metube).

Do you have some kind of sandbox solution which behaves as an original chomikuj.pl, so that I could test my code against, without wasting my traffic on chomikuj?

**Comment by plintx** [comment]
Hi @shalak 
I don't have any sandbox. When i writing this piece of code downloading own files was for free, without wasting traffic. Does it work differently now?

**Comment by shalak** [comment]
Huh, most likely you're right ;) Thanks for the tip!
